/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 21:03:15 GMT 2023
 */

package smarthouse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.nio.channels.DatagramChannel;
import java.nio.channels.FileChannel;
import java.nio.channels.NonReadableChannelException;
import java.nio.channels.NotYetConnectedException;
import java.nio.channels.SocketChannel;
import java.time.LocalDate;
import java.time.Period;
import java.time.chrono.IsoChronology;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.function.BiFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockFileReader;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;
import smarthouse.CasaInteligente;
import smarthouse.Comercializador;
import smarthouse.Estatisticas;
import smarthouse.Periodo;
import smarthouse.Simulador;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Estatisticas_ESTest extends Estatisticas_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      Simulador simulador0 = new Simulador();
      Map<String, Comercializador> map0 = simulador0.getComercializadores();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Period period0 = Period.ofDays(1);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Integer integer0 = new Integer(1);
      CasaInteligente casaInteligente0 = new CasaInteligente();
      BiFunction<Object, Object, CasaInteligente> biFunction0 = (BiFunction<Object, Object, CasaInteligente>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn(casaInteligente0).when(biFunction0).apply(any() , any());
      hashMap0.compute(integer0, biFunction0);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      linkedList0.add(periodo0);
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, map0, linkedList0);
      linkedList0.add(periodo0);
      // Undeclared exception!
      try { 
        estatisticas0.estatistica1();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("smarthouse.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      Simulador simulador0 = new Simulador();
      Map<String, Comercializador> map0 = simulador0.getComercializadores();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Period period0 = Period.ofDays(1);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Integer integer0 = new Integer(1);
      Comercializador comercializador0 = new Comercializador((String) null, 0, 0);
      CasaInteligente casaInteligente0 = new CasaInteligente("| 3. Gerir uma casa                                |", 0, comercializador0);
      BiFunction<Object, Object, CasaInteligente> biFunction0 = (BiFunction<Object, Object, CasaInteligente>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn(casaInteligente0).when(biFunction0).apply(any() , any());
      hashMap0.compute(integer0, biFunction0);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      linkedList0.add(periodo0);
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, map0, linkedList0);
      estatisticas0.estatistica1();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Simulador simulador0 = new Simulador();
      Map<String, Comercializador> map0 = simulador0.getComercializadores();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Period period0 = Period.ofDays(1);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      linkedList0.add(periodo0);
      Map<Integer, CasaInteligente> map1 = simulador0.getCasasInteligentes();
      Estatisticas estatisticas0 = new Estatisticas(map1, map0, linkedList0);
      Scanner scanner0 = new Scanner("");
      // Undeclared exception!
      try { 
        estatisticas0.estatistica4(scanner0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      linkedList0.add(periodo0);
      Estatisticas estatisticas0 = new Estatisticas((Map<Integer, CasaInteligente>) null, hashMap0, linkedList0);
      Scanner scanner0 = new Scanner("M^(d=O");
      // Undeclared exception!
      try { 
        estatisticas0.estatistica4(scanner0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"M^(d=O\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Simulador simulador0 = new Simulador();
      Map<Integer, CasaInteligente> map0 = simulador0.getCasasInteligentes();
      Map<String, Comercializador> map1 = simulador0.getComercializadores();
      Estatisticas estatisticas0 = new Estatisticas(map0, map1, (List<Periodo>) null);
      // Undeclared exception!
      try { 
        estatisticas0.estatistica4((Scanner) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("smarthouse.Periodo", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Simulador simulador0 = new Simulador(true);
      Map<Integer, CasaInteligente> map0 = simulador0.getCasasInteligentes();
      Map<String, Comercializador> map1 = simulador0.getComercializadores();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(map0, map1, linkedList0);
      Scanner scanner0 = new Scanner("-+Bf%iNp_9D zoHNr|");
      estatisticas0.estatistica3(scanner0);
      // Undeclared exception!
      try { 
        estatisticas0.estatistica3(scanner0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Simulador simulador0 = new Simulador(true);
      Map<Integer, CasaInteligente> map0 = simulador0.getCasasInteligentes();
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(map0, hashMap0, linkedList0);
      SocketChannel socketChannel0 = SocketChannel.open();
      Scanner scanner0 = new Scanner(socketChannel0);
      // Undeclared exception!
      try { 
        estatisticas0.estatistica3(scanner0);
        fail("Expecting exception: NotYetConnectedException");
      
      } catch(NotYetConnectedException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      HashMap<String, Comercializador> hashMap1 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, hashMap1, linkedList0);
      // Undeclared exception!
      try { 
        estatisticas0.estatistica3((Scanner) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("smarthouse.Comercializador", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas((Map<Integer, CasaInteligente>) null, hashMap0, linkedList0);
      Scanner scanner0 = new Scanner(":u>xIc(mcoS*o!ot5");
      scanner0.close();
      // Undeclared exception!
      try { 
        estatisticas0.estatistica3(scanner0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, (Map<String, Comercializador>) null, linkedList0);
      // Undeclared exception!
      try { 
        estatisticas0.estatistica2();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Simulador simulador0 = new Simulador();
      Map<Integer, CasaInteligente> map0 = simulador0.getCasasInteligentes();
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(map0, hashMap0, linkedList0);
      MockFile mockFile0 = new MockFile("xzc~");
      File file0 = MockFile.createTempFile("nFv", "{l|TZ2wEs.W[=1SV", (File) mockFile0);
      MockFileReader mockFileReader0 = new MockFileReader(file0);
      Scanner scanner0 = new Scanner(mockFileReader0);
      // Undeclared exception!
      try { 
        estatisticas0.escolherEstatistica(scanner0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      Simulador simulador0 = new Simulador(true);
      Map<String, Comercializador> map0 = simulador0.getComercializadores();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, map0, linkedList0);
      DatagramChannel datagramChannel0 = DatagramChannel.open();
      Scanner scanner0 = new Scanner(datagramChannel0);
      // Undeclared exception!
      try { 
        estatisticas0.escolherEstatistica(scanner0);
        fail("Expecting exception: NotYetConnectedException");
      
      } catch(NotYetConnectedException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      HashMap<String, Comercializador> hashMap1 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, hashMap1, linkedList0);
      MockFile mockFile0 = new MockFile(".o");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0, false);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      Scanner scanner0 = new Scanner(fileChannel0);
      // Undeclared exception!
      try { 
        estatisticas0.escolherEstatistica(scanner0);
        fail("Expecting exception: NonReadableChannelException");
      
      } catch(NonReadableChannelException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      HashMap<String, Comercializador> hashMap1 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, hashMap1, linkedList0);
      // Undeclared exception!
      try { 
        estatisticas0.escolherEstatistica((Scanner) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("smarthouse.Estatisticas", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      HashMap<String, Comercializador> hashMap1 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, hashMap1, linkedList0);
      Scanner scanner0 = new Scanner("NEUTRAL");
      scanner0.close();
      // Undeclared exception!
      try { 
        estatisticas0.escolherEstatistica(scanner0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Scanner closed
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      Simulador simulador0 = new Simulador();
      Map<String, Comercializador> map0 = simulador0.getComercializadores();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, map0, linkedList0);
      estatisticas0.estatistica2();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      HashMap<String, Comercializador> hashMap1 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, hashMap1, linkedList0);
      Scanner scanner0 = new Scanner("{A2pt+PXrk>(");
      estatisticas0.escolherEstatistica(scanner0);
      assertEquals("java.util.Scanner[delimiters=\\p{javaWhitespace}+][position=12][match valid=true][need input=false][source closed=true][skipped=false][group separator=\\x{2c}][decimal separator=\\x{2e}][positive prefix=][negative prefix=\\Q-\\E][positive suffix=][negative suffix=][NaN string=\\Q\uFFFD\\E][infinity string=\\Q\u221E\\E]", scanner0.toString());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Simulador simulador0 = new Simulador(true);
      Map<Integer, CasaInteligente> map0 = simulador0.getCasasInteligentes();
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(map0, hashMap0, linkedList0);
      estatisticas0.estatistica4((Scanner) null);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas((Map<Integer, CasaInteligente>) null, hashMap0, linkedList0);
      Scanner scanner0 = new Scanner(":u>xIc(mcoS*o!ot5");
      Comercializador comercializador0 = new Comercializador(":u>xIc(mcoS*o!ot5", 1.0, 1.0);
      hashMap0.put(":u>xIc(mcoS*o!ot5", comercializador0);
      estatisticas0.estatistica3(scanner0);
      assertEquals(10, scanner0.radix());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Simulador simulador0 = new Simulador(true);
      Map<Integer, CasaInteligente> map0 = simulador0.getCasasInteligentes();
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(map0, hashMap0, linkedList0);
      Comercializador comercializador0 = new Comercializador("smarthouse.SmartSpeaker", 1.0, 350.0691992);
      hashMap0.put("x]JQoAkx.K:", comercializador0);
      linkedList0.add((Periodo) null);
      estatisticas0.estatistica2();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas((Map<Integer, CasaInteligente>) null, hashMap0, linkedList0);
      Scanner scanner0 = new Scanner("2");
      estatisticas0.escolherEstatistica(scanner0);
      assertEquals("java.util.Scanner[delimiters=\\p{javaWhitespace}+][position=1][match valid=true][need input=false][source closed=true][skipped=false][group separator=\\x{2c}][decimal separator=\\x{2e}][positive prefix=][negative prefix=\\Q-\\E][positive suffix=][negative suffix=][NaN string=\\Q\uFFFD\\E][infinity string=\\Q\u221E\\E]", scanner0.toString());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Simulador simulador0 = new Simulador(true);
      Map<Integer, CasaInteligente> map0 = simulador0.getCasasInteligentes();
      HashMap<String, Comercializador> hashMap0 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(map0, hashMap0, linkedList0);
      Comercializador comercializador0 = new Comercializador("smarthouse.SmartSpeaker", 1.0, 350.0691992);
      hashMap0.put("x]JQoAkx.K:", comercializador0);
      estatisticas0.estatistica2();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      Simulador simulador0 = new Simulador();
      Map<String, Comercializador> map0 = simulador0.getComercializadores();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Period period0 = Period.ofDays(1);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      linkedList0.add(periodo0);
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, map0, linkedList0);
      estatisticas0.estatistica1();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HashMap<Integer, CasaInteligente> hashMap0 = new HashMap<Integer, CasaInteligente>();
      HashMap<String, Comercializador> hashMap1 = new HashMap<String, Comercializador>();
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      Estatisticas estatisticas0 = new Estatisticas(hashMap0, hashMap1, linkedList0);
      estatisticas0.estatistica1();
  }
}
