/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 21:09:56 GMT 2023
 */

package smarthouse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Random;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;
import smarthouse.Formula;
import smarthouse.SmartBulb;
import smarthouse.SmartCamera;
import smarthouse.SmartDevice;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Formula_ESTest extends Formula_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Formula formula0 = Formula.formula0();
      SmartDevice.Modo smartDevice_Modo0 = SmartDevice.Modo.ON;
      SmartCamera smartCamera0 = new SmartCamera(smartDevice_Modo0, (-133), (-133), (-133), 5.0);
      double double0 = formula0.precoDiario(smartCamera0, (-133), 5.0);
      assertEquals((-3591.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Formula.getFormula((Random) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("smarthouse.Formula", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Formula formula0 = Formula.formula3();
      SmartCamera smartCamera0 = new SmartCamera();
      double double0 = formula0.precoDiario(smartCamera0, 350.0, 350.0);
      assertEquals(175.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Formula formula0 = Formula.formula1();
      SmartDevice.Modo smartDevice_Modo0 = SmartDevice.Modo.OFF;
      SmartBulb smartBulb0 = new SmartBulb(smartDevice_Modo0, 0, 0, 0);
      double double0 = formula0.precoDiario(smartBulb0, 0.0, 0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Formula formula0 = Formula.formula2();
      assertNotNull(formula0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom(380L);
      Formula formula0 = Formula.getFormula(mockRandom0);
      assertNotNull(formula0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      org.evosuite.runtime.Random.setNextRandom(1447);
      Formula formula0 = Formula.getFormula(mockRandom0);
      assertNotNull(formula0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Formula formula0 = Formula.formula0();
      // Undeclared exception!
      try { 
        formula0.precoDiario((SmartDevice) null, (-721.04182), 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("smarthouse.Formula", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      mockRandom0.nextGaussian();
      mockRandom0.nextLong();
      Formula formula0 = Formula.getFormula(mockRandom0);
      assertNotNull(formula0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      mockRandom0.nextGaussian();
      Formula formula0 = Formula.getFormula(mockRandom0);
      assertNotNull(formula0);
  }
}
