/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 21:11:50 GMT 2023
 */

package smarthouse;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import smarthouse.LinhaIncorretaException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class LinhaIncorretaException_ESTest extends LinhaIncorretaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinhaIncorretaException linhaIncorretaException0 = new LinhaIncorretaException();
  }
}
