/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 22:24:33 GMT 2023
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedReader;
import java.io.FileDescriptor;
import java.io.StringReader;
import java.nio.channels.NotYetConnectedException;
import java.nio.channels.SocketChannel;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.LinkedList;
import java.util.NoSuchElementException;
import java.util.Scanner;
import main.java.Periodo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Periodo_ESTest extends Periodo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay(0, 1);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      LocalDate localDate1 = periodo0.getInicio();
      assertSame(localDate0, localDate1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      LocalDate localDate1 = periodo0.getFim();
      assertSame(localDate0, localDate1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      linkedList0.add(periodo0);
      SocketChannel socketChannel0 = SocketChannel.open();
      Scanner scanner0 = new Scanner(socketChannel0);
      // Undeclared exception!
      try { 
        Periodo.escolherPeriodo(linkedList0, scanner0);
        fail("Expecting exception: NotYetConnectedException");
      
      } catch(NotYetConnectedException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      StringReader stringReader0 = new StringReader("+--------------------------------------------------+");
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours((-1));
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      linkedList0.add(periodo0);
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 1);
      Scanner scanner0 = new Scanner(bufferedReader0);
      // Undeclared exception!
      try { 
        Periodo.escolherPeriodo(linkedList0, scanner0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"+--------------------------------------------------+\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      Scanner scanner0 = new Scanner(mockFileInputStream0);
      linkedList0.add((Periodo) null);
      // Undeclared exception!
      try { 
        Periodo.escolherPeriodo(linkedList0, scanner0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.Periodo", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Periodo periodo0 = null;
      try {
        periodo0 = new Periodo((Periodo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.Periodo", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      Periodo periodo1 = new Periodo(periodo0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-872L));
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      Periodo periodo1 = periodo0.clone();
      boolean boolean0 = periodo1.equals(periodo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      Periodo periodo1 = periodo0.clone();
      // Undeclared exception!
      try { 
        periodo0.equals(periodo1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.Periodo", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      boolean boolean0 = periodo0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      boolean boolean0 = periodo0.equals(periodo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      boolean boolean0 = periodo0.equals("Periodo de 2014-02-14 a 2014-02-14");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      SocketChannel socketChannel0 = SocketChannel.open();
      Scanner scanner0 = new Scanner(socketChannel0);
      Periodo periodo0 = Periodo.escolherPeriodo(linkedList0, scanner0);
      assertNull(periodo0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Periodo periodo0 = new Periodo(localDate0, localDate0);
      LinkedList<Periodo> linkedList0 = new LinkedList<Periodo>();
      linkedList0.add(periodo0);
      Scanner scanner0 = new Scanner("");
      // Undeclared exception!
      try { 
        Periodo.escolherPeriodo(linkedList0, scanner0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      String string0 = periodo0.toString();
      assertEquals("Periodo de null a null", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      LocalDate localDate0 = periodo0.getInicio();
      assertNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Periodo periodo0 = new Periodo((LocalDate) null, (LocalDate) null);
      LocalDate localDate0 = periodo0.getFim();
      assertNull(localDate0);
  }
}
