/*
 * This file was automatically generated by EvoSuite
 * Tue May 09 08:52:38 GMT 2023
 */

package src.main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import src.main.java.LinhaIncorretaException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LinhaIncorretaException_ESTest extends LinhaIncorretaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinhaIncorretaException linhaIncorretaException0 = new LinhaIncorretaException();
  }
}
