/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 22:27:15 GMT 2023
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import main.java.LinhaIncorretaException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LinhaIncorretaException_ESTest extends LinhaIncorretaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinhaIncorretaException linhaIncorretaException0 = new LinhaIncorretaException();
  }
}
